services:
  btc-node:
    build: btc-node
    ports:
      - 127.0.0.1:18443:18443 # RPC port
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          '-u',
          'user:password',
          '--data-binary',
          '{"jsonrpc": "2.0", "method": "getblockcount", "params": []}',
          '-H',
          'content-type: text/plain;',
          'http://btc-node:18443'
        ]
      interval: 10s
      timeout: 10s
      retries: 3

  wasabi-backend:
    build: wasabi-backend
    environment:
      - WASABI_BIND=http://0.0.0.0:37127
    depends_on:
      btc-node:
        condition: service_healthy

  wasabi-client:
    build: wasabi-client
    depends_on:
      - wasabi-backend
