name: Upload wasabi-clients

on:
  push:
    branches:
      - main
    paths:
      - 'containers/wasabi-clients/**'

jobs:
  list-wasabi-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Wasabi versions
        id: list-versions
        run: |
          cd containers/wasabi-clients
          VERSIONS=$(ls -d */ | cut -f1 -d'/' | sort -V | jq -R . | jq -s . | tr -d '\n ')
          echo "versions=$VERSIONS" >> "$GITHUB_OUTPUT"
    outputs:
      versions: ${{ steps.list-versions.outputs.versions }}

  docker:
    needs: list-wasabi-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.list-wasabi-versions.outputs.versions) }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{ defaultContext }}:containers/wasabi-clients/${{ matrix.version }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wasabi-client:${{ matrix.version }}